name: MLOpos CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run data processing Tests
      run: |
        python src/data/run_processing.py \
           --input data/raw/house_data.csv \
           --output data/processed/cleaned_house_data.csv

    - name: Feature Engineering
      run: |
        python src/features/engineer.py \
           --input data/processed/cleaned_house_data.csv \
           --output data/processed/feature_engineered_data.csv \
           --preprocessor models/trained/preprocessor.pkl


    - name: Mlflow setup
      run: |
        docker pull ghcr.io/mlflow/mlflow:latest
        docker run -d -p 5555:5000  ghcr.io/mlflow/mlflow:latest \
          mlflow server --host 0.0.0.0 \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root /tmp/mlruns

    - name: Train the model
      run: |
        python src/models/train_model.py \
           --config configs/model_config.yaml \
           --data data/processed/feature_engineered_data.csv \
           --models-dir models/trained/ \
           --mlflow-tracking-uri http://mlflow:5555